### PR TITLE
Re-add accidentally removed check for expected socat errors

### PR DESCRIPTION
**Pull request by pabs3**
Partially-reverts: commit c688351d1ac7c4c9b669196ab4e1c40631a344e1

### CODE REVIEW

**Comment by hoyon** [comment]
Hi @pabs3, thanks for all the PRs! I've merged the rest of the them but for this one I removed this bit because the test was failing with the following output and I didn't have time to investigate further. It seems like socat no longer contains any errors in this test case? Interesting that it still passes on CI and presumably on your machine.

```
make stop
./wrapper "stop"
./stop
++ test -n ''
++ exec ./env ./stop
/home/hoyon/code/mpv-mpris/test/env ./stop
++ basename ./stop
+ test=stop
+ '[' -z '' ']'
+ export MPV_MPRIS_TEST_PLUGIN=../mpris.so
+ MPV_MPRIS_TEST_PLUGIN=../mpris.so
+ '[' -z '' ']'
+ export MPV_MPRIS_TEST_PLAY=/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga
+ MPV_MPRIS_TEST_PLAY=/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga
+ '[' -z '' ']'
+ export MPV_MPRIS_TEST_MPV_IPC=.
+ MPV_MPRIS_TEST_MPV_IPC=.
+ '[' -z '' ']'
+ export MPV_MPRIS_TEST_LOG=.
+ MPV_MPRIS_TEST_LOG=.
+ '[' -z '' ']'
+ MPV_MPRIS_TEST_DBUS=.
+ '[' -z '' ']'
+ MPV_MPRIS_TEST_XAUTH=.
+ '[' -z '' ']'
+ MPV_MPRIS_TEST_TMP=.
+ '[' -n ../mpris.so ']'
+ '[' '!' -f ../mpris.so ']'
+ '[' '!' -r ../mpris.so ']'
+ '[' '!' -x ../mpris.so ']'
+ '[' '!' -f /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga ']'
+ '[' '!' -r /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga ']'
+ writable_dir .
+ '[' '!' -d . ']'
+ '[' '!' -r . ']'
+ '[' '!' -w . ']'
+ '[' '!' -x . ']'
+ writable_dir .
+ '[' '!' -d . ']'
+ '[' '!' -r . ']'
+ '[' '!' -w . ']'
+ '[' '!' -x . ']'
+ writable_dir .
+ '[' '!' -d . ']'
+ '[' '!' -r . ']'
+ '[' '!' -w . ']'
+ '[' '!' -x . ']'
+ writable_dir .
+ '[' '!' -d . ']'
+ '[' '!' -r . ']'
+ '[' '!' -w . ']'
+ '[' '!' -x . ']'
+ writable_dir .
+ '[' '!' -d . ']'
+ '[' '!' -r . ']'
+ '[' '!' -w . ']'
+ '[' '!' -x . ']'
+ export -n MPV_MPRIS_TEST_DBUS MPV_MPRIS_TEST_XAUTH MPV_MPRIS_TEST_TMP
+ xvfb-run --help
+ grep -- --auto-display
                                    --server-num (deprecated, use --auto-display
-d        --auto-display            use the X server to find a display number
+ xvfb_auto=--auto-display
+ exec env MPV_MPRIS_TEST_NAME=stop XDG_RUNTIME_DIR=. TEMPDIR=. TMPDIR=. TEMP=. TMP=. dbus-run-session -- xvfb-run --auto-display --error-file ./stop.xvfb.log -f ./stop.Xauthority ./stop
./stop
++ test -n stop
+++ basename ./stop
++ test=stop
++ '[' stop = setup ']'
++ input_json=./stop.mpv.ipc.input.json
++ output_json=./stop.mpv.ipc.output.json
++ ipc=./stop.mpv.ipc
++ log_prefix=./stop
++ mpv_log=./stop.mpv.log
++ socat_log=./stop.socat.log
++ file=/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga
++ params=()
++ '[' -n 1 ']'
++ '[' 1 -ne 0 ']'
++ params+=("--pause")
++ '[' -n ../mpris.so ']'
++ params+=("--load-scripts=no" "--script=$MPV_MPRIS_TEST_PLUGIN")
++ unset MPV_MPRIS_TEST_PLUGIN MPV_MPRIS_TEST_PLAY MPV_MPRIS_TEST_MPV_IPC MPV_MPRIS_TEST_LOG
++ echo DISPLAY=:1
DISPLAY=:1
++ echo DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-V745Sm5Fds,guid=8b0fe2c5662b03a9cb498f4c622c92fc
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-V745Sm5Fds,guid=8b0fe2c5662b03a9cb498f4c622c92fc
++ sleep 2
++ mpv --pause --load-scripts=no --script=../mpris.so --vo=null --ao=null --msg-time --msg-module --msg-level=cplayer=trace,mpris=trace --log-file=./stop.mpv.log --input-ipc-server=./stop.mpv.ipc /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga
+++ awk '/statusline.*Paused/{print>"/dev/stdout";next} 1'
[cplayer] mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.17.100
[cplayer]    libavcodec      59.18.100
[cplayer]    libavformat     59.16.100
[cplayer]    libswscale      6.4.100
[cplayer]    libavfilter     8.24.100
[cplayer]    libswresample   4.3.100
[cplayer] FFmpeg version: n5.0
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca
[cplayer] List of enabled features: alsa asm cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua luajit memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-static stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
[cplayer] Command line options: '--pause' '--load-scripts=no' '--script=../mpris.so' '--vo=null' '--ao=null' '--msg-time' '--msg-module' '--msg-level=cplayer=trace,mpris=trace' '--log-file=./stop.mpv.log' '--input-ipc-server=./stop.mpv.ipc' '/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga'
[cplayer] mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.17.100
[cplayer]    libavcodec      59.18.100
[cplayer]    libavformat     59.16.100
[cplayer]    libswscale      6.4.100
[cplayer]    libavfilter     8.24.100
[cplayer]    libswresample   4.3.100
[cplayer] FFmpeg version: n5.0
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca
[cplayer] List of enabled features: alsa asm cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua luajit memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-static stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/hoyon/.config/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'audio-display' = 'no' (flags = 4)
[cplayer] Setting option 'pause' = '' (flags = 8)
[cplayer] Setting option 'load-scripts' = 'no' (flags = 8)
[cplayer] Setting option 'scripts-append' = '../mpris.so' (flags = 8)
[cplayer] Setting option 'vo' = 'null' (flags = 8)
[cplayer] Setting option 'ao' = 'null' (flags = 8)
[cplayer] Setting option 'msg-time' = '' (flags = 8)
[cplayer] Setting option 'msg-module' = '' (flags = 8)
[cplayer] Setting option 'msg-level' = 'cplayer=trace,mpris=trace' (flags = 8)
[cplayer] Setting option 'log-file' = './stop.mpv.log' (flags = 8)
[cplayer] Setting option 'input-ipc-server' = './stop.mpv.ipc' (flags = 8)
[  0.003964]      mpris: Loading SO plugin ../mpris.so...
[  0.004044]    cplayer: Waiting for scripts...
[  0.005749]    cplayer: Run command: osd-overlay, flags=64, args=[id="1", format="ass-events", data="", res_x="0", res_y="0", z="0", hidden="no", compute_bounds="no"]
[  0.012436]    cplayer: Run command: define-section, flags=64, args=[name="input_console", contents="", flags="default"]
[  0.012466]    cplayer: Run command: enable-section, flags=64, args=[name="input_console", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.012487]    cplayer: Run command: define-section, flags=64, args=[name="input_forced_console", contents="", flags="force"]
[  0.012496]    cplayer: Run command: enable-section, flags=64, args=[name="input_forced_console", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.012709]    cplayer: Run command: define-section, flags=64, args=[name="showhide", contents="mouse_move script-binding osc/__keybinding1\nmouse_leave script-binding osc/__keybinding2\n", flags="force"]
[  0.012764]    cplayer: Run command: define-section, flags=64, args=[name="showhide_wc", contents="mouse_move script-binding osc/__keybinding3\nmouse_leave script-binding osc/__keybinding4\n", flags="force"]
[  0.012797]    cplayer: Run command: enable-section, flags=64, args=[name="showhide", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.012811]    cplayer: Run command: enable-section, flags=64, args=[name="showhide_wc", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.012841]    cplayer: Run command: define-section, flags=64, args=[name="input", contents="mbtn_left script-binding osc/__keybinding5\nshift+mbtn_left script-binding osc/__keybinding6\nmbtn_right script-binding osc/__keybinding7\nmbtn_mid script-binding osc/__keybinding8\nwheel_up script-binding osc/__keybinding9\nwheel_down script-binding osc/__keybinding10\nmbtn_left_dbl ignore\nshift+mbtn_left_dbl ignore\nmbtn_right_dbl ignore\n", flags="force"]
[  0.012893]    cplayer: Run command: enable-section, flags=64, args=[name="input", flags=""]
[  0.012910]    cplayer: Run command: define-section, flags=64, args=[name="window-controls", contents="mbtn_left script-binding osc/__keybinding11\n", flags="force"]
[  0.012927]    cplayer: Run command: enable-section, flags=64, args=[name="window-controls", flags=""]
[  0.012943]    cplayer: Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-visibility=auto"]
[  0.012966]    cplayer: Set property: shared-script-properties -> 1
[  0.012988]    cplayer: Run command: disable-section, flags=64, args=[name="input"]
[  0.013011]    cplayer: Run command: disable-section, flags=64, args=[name="window-controls"]
[  0.013028]    cplayer: Run command: define-section, flags=64, args=[name="input_stats", contents="", flags="default"]
[  0.013054]    cplayer: Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[  0.013075]    cplayer: Set property: shared-script-properties -> 1
[  0.013091]    cplayer: Run command: enable-section, flags=64, args=[name="input_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.013123]    cplayer: Run command: define-section, flags=64, args=[name="input_forced_stats", contents="", flags="force"]
[  0.013138]    cplayer: Run command: enable-section, flags=64, args=[name="input_forced_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.013162]    cplayer: Done loading scripts.
[  0.013202]    cplayer: Running hook: ytdl_hook/on_load
[  0.013414]    cplayer: Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[  0.013440]    cplayer: Set property: shared-script-properties -> 1
[  0.013805]    cplayer: Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[  0.013827]    cplayer: Set property: shared-script-properties -> 1
[  0.013893]    cplayer: Run command: osd-overlay, flags=64, args=[id="1", format="ass-events", data="", res_x="854", res_y="854", z="1000", hidden="no", compute_bounds="no"]
[  0.019811]    cplayer: Opening done: /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga
[  0.025192]    cplayer: Running hook: ytdl_hook/on_pre+ status Paused
+ playerctl status
+ grep '^Paused$'
Paused
+ check pause true
+ prop pause
+ jq --null-input --compact-output --arg prop pause '{command: ["get_property", $prop]}'
+ cat ./stop.mpv.ipc.input.json
{"command":["get_property","pause"]}
+ rm -f ./stop.socat.log
+ socat -lf./stop.socat.log - ./stop.mpv.ipc
+ cat ./stop.socat.log
+ test '!' -s ./stop.socat.log
+ cat ./stop.mpv.ipc.output.json
{"data":true,"request_id":0,"error":"success"}
+ test -s ./stop.mpv.ipc.output.json
+ val true
+ jq --exit-status --null-input 'inputs // {} | try (.data == true and .error == "success") catch false'
true
+ playerctl stop
+ sleep 2
loaded
[  0.025262]    cplayer:  (+) Audio --aid=1 (vorbis 2ch 48000Hz)
[  0.025766]    cplayer: Starting playback...
[  0.026095]    cplayer: AO: [null] 48000Hz stereo 2ch floatp
[  0.026100]    cplayer: AO: Description: Null audio output
[  0.026307]    cplayer: audio ready
[  0.026312]    cplayer: starting audio playback
[  0.026319]    cplayer: playback restart complete @ 0.000000, audio=playing, video=eof (paused)
[  0.026748]    cplayer: Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[  0.026777]    cplayer: Set property: shared-script-properties -> 1
[  0.026832]    cplayer: Run command: define-section, flags=64, args=[name="input_osc", contents="", flags="default"]
[  0.026849]    cplayer: Run command: enable-section, flags=64, args=[name="input_osc", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.026865]    cplayer: Run command: define-section, flags=64, args=[name="input_forced_osc", contents="", flags="force"]
[  0.026878]    cplayer: Run command: enable-section, flags=64, args=[name="input_forced_osc", flags="allow-hide-cursor+allow-vo-dragging"]
[  0.057292]    cplayer: Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[  0.057321]    cplayer: Set property: shared-script-properties -> 1
[  0.063404] statusline: (Paused) A: 00:00:00 / 00:00:06 (0%)
[  2.024386]    cplayer: Run command: stop, flags=64, args=[flags=""]
[  2.024401]    cplayer: EOF code: 4  
[  2.024514]    cplayer: Terminating demuxers...
[  2.024632]    cplayer: Done terminating demuxers.
[  2.024653]    cplayer: finished playback, success (reason 2)
[  2.024658]    cplayer: 
[  2.024662]    cplayer: Exiting... (End of file)
[  2.025027]      mpris: Exiting...
[  2.025613]    cplayer: Run command: change-list, flags=64, args=[name="shared-script-properties", operation="remove", value="osc-margins"]
[  2.025648]    cplayer: Set property: shared-script-properties -> 1
+ ret_ipc=0
+ prop pause
+ jq --null-input --compact-output --arg prop pause '{command: ["get_property", $prop]}'
+ cat ./stop.mpv.ipc.input.json
{"command":["get_property","pause"]}
+ rm -f ./stop.socat.log
+ socat -lf./stop.socat.log - ./stop.mpv.ipc
+ ret_ipc=255
+ cat ./stop.mpv.ipc.output.json
+ test '!' -s ./stop.mpv.ipc.output.json
+ '[' 255 -eq 0 ']'
+ '[' '!' -s ./stop.socat.log ']'
+ echo 'socat log should contain an error!'
socat log should contain an error!
+ playerctl status
+ grep '^No players found$'
No players found
+ '[' 255 -eq 0 ']'
+ '[' '!' -s ./stop.socat.log ']'
+ exit 1
test stop: stderr not empty!
test stop: start of stderr ---------------------
socat log should contain an error!
test stop: end of stderr -----------------------
test stop: stderr not empty!
test stop: failed with exit code 1
make: *** [Makefile:18: stop] Error 1
```

**Comment by pabs3** [comment]
Hmm, your socat returns 255 and no log while mine returns 1 and a log:

2022/03/12 21:34:53 socat[1557148] E connect(7, AF=1 "./stop.mpv.ipc", 16): Connection refused

I have socat version 1.7.4.1-3 from Debian bookworm, which version do you have?

To eliminate timing issues, could you change the sleep after playerctl
stop from 2 seconds to 20 and see if that helps?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by hoyon** [comment]
Increasing the sleep time has no effect - the test still fails and socat still exists with 255.

I have socat 1.7.4.3-1 from arch linux.

**Comment by pabs3** [comment]
I updated the Debian package to 1.7.4.3-1 and now I get the same error
as you. I'll have a look at what changed to cause this.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
OK, this is an issue caused by changes in socat 1.7.4.3 upstream.

In both versions, when you pass an argument to socat that contains a
forward slash character (/) then it interprets it as a filename, then
detects that it is a socket and connects to it.

The change in 1.7.4.3 is that there is some sort of fallback that means
that after the connect failed it means the detection failed so socat
fails with 255 and doesn't log the error. Kind of makes sense I guess.

The right fix seems to be to not auto-detect by using UNIX-CONNECT: to
force it to connect to a Unix socket. Since we know that the argument
we are supplying is definitely a Unix socket, we want this anyway, just
in case mpv gets broken and creates a regular file instead of a socket.

Incidentally, this also fixes the case when the argument does not
contain a forward slash so isn't interpreted as a filename and thus
isn't used as a Unix socket. Currently the mpv-mpris test suite doesn't
create filenames without slashes, but it is a good idea to fix this
case too just in case things change in the future.

I've filed another PR for the UNIX-CONNECT part, please merge that PR
*first* and then this PR. The order is important to avoid failures due
to this issue during future git bisects on unrelated issues.

https://github.com/hoyon/mpv-mpris/pull/72

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
PS: once you have merged #72 and then #66, please make a new release.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@hoyon thanks for merging! A new release would be appreciated too.

PS: I contacted the socat author and they reproduced the behaviour
change and said that they will fix the issue soon.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Pull request merged**
