### PR TITLE
include date metadata

### PR DESCRIPTION
**Pull request by Phate6660**
Just added this in because I tag all of my music with the year of release, and I noticed that this didn't support the date tag. Figured I'd open a PR and share the whole one line that I added.

### CODE REVIEW

**Comment by hoyon** [comment]
Thanks for the contribution!

After some quick googling, it doesn't seem like `xesam:date` is the correct property. The list of recommended mpris properties is available [here](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata).

It seems like `xesam:contentCreated` is the most appropriate property. I've had a look at what [Rhythmbox does](https://gitlab.gnome.org/GNOME/rhythmbox/blob/master/plugins/mpris/rb-mpris-plugin.c#L496) and they seem to set that to the first of January of the release year. Rhythmbox has one of the most complete mpris implementations I've seen so it would probably be best to follow what it does.

Could you perhaps expand your 1 line PR to instead use `xesam:contentCreated`?

**Comment by Phate6660** [comment]
I can do that. To be honest, I just quickly threw it in there because `mpv` displayed the tag as "Date". Since it worked, I just figured it was ok.

**Comment by hoyon** [comment]
The issue is that `metadata/by-key/Date` seems to give the year of release eg "2020" however if you look at the links above, `xesam:contentCreated` should be an ISO8601 timestamp so for 2020 it would be `2020-01-01T00:00:00Z`.

Another issue is that mpv lacks documentation for what `metadata/by-key/Date` actually returns so it might not be the year for certain file formats. However I think it's safe to assume it's always the year for now.

**Comment by hoyon** [comment]
I decided to give this a shot myself. 

Closing this for now.

**Pull request closed without merging**
