### PR TITLE
Make playlist-next and playlist-previous function properly

### PR DESCRIPTION
**Pull request by NaabZer**
Changed the commands for Next and Previous to make them work correctly with mpv.

### CODE REVIEW

**Comment by hoyon** [comment]
Hi, Thanks for the PR.

As far as I can tell, adding the "force" parameter simply causes mpv to terminate if it can't go to the next/previous track in the playlist. I'm not sure if this should be the desired behaviour, considering mpv doesn't do this by default.

**Comment by NaabZer** [comment]
That seems reasonable, for me it doesn't work unless you use the "force" parameter, but like you mentioned, it terminates if you don't have a playlist or try to go past the last track in a playlist..

**Comment by NaabZer** [comment]
I did some more testing and the problem was related to the way I started mpv (via mps-youtube), it created several instances of mpv, which caused problems, I think the "Force" might've killed one of the processes so the other one worked.

**Comment by hoyon** [comment]
Sorry for the late reply. Glad you found your issue. Closing since weak is the default anyway.

**Pull request closed without merging**
